name: 'Get Organization Info'
description: 'An action to retrieve information about an organization, its members, teams, and repositories.'
branding:
  icon: 'info'
  color: 'yellow'

inputs:
  secretToken:
    description: 'Enter the secret token'
    required: true
  outputFileName:
    description: 'Enter how the file should be called.'
    required: true


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - run: |
        ORG_NAME=${{ github.repository_owner }}
        GITHUB_TOKEN=${{ inputs.secretToken }}

        timestamp=$(date)

        ORG_API_URL="https://api.github.com/orgs/$ORG_NAME"

        # Send a GET request to GH API and retrieve members from organization
        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$ORG_API_URL/members")
        if [[ $response == *"Bad credentials"* ]]; then
          cat >${{ inputs.outputFileName }}.md <<EOF
        Bad credentials: The provided token has no access for running this script!

        Follow the Readme.md file for more information about the installation
        EOF
        else
          # Get organization members
          members=$(echo "$response" | jq -r '.[].login')

          # Username and roles:
          users=()
          roles=()
          for username in $members; do
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$ORG_API_URL/memberships/$username")

            role=$(echo "$response" | jq -r '.role')
            users+=("$username")
            roles+=("$role")

          done

          # Name of members
          names=()
          for member_id in $members; do
            USER_API_URL="https://api.github.com/users"

            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$USER_API_URL/$member_id")

            member_name=$(echo "$response" | jq -r '.name')
            names+=("$member_name")

          done

          # Teams
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$ORG_API_URL/teams")

          declare -A teams
          while IFS= read -r team_info; do
            team_id=$(echo "$team_info" | jq -r '.id')
            team_name=$(echo "$team_info" | jq -r '.name')
            teams[$team_id]=$team_name
          done <<<"$(echo "$response" | jq -c '.[]')"

          # Team's members
          declare -A team_content
          for id in "${!teams[@]}"; do
            TEAM_API_URL="https://api.github.com/teams"

            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$TEAM_API_URL/$id/members")
            team_member_name=$(echo "$response" | jq -r '.[].login')

            # key = name of team, value = members which belongs to that team
            team_content["${teams[$id]}"]="$team_member_name"

          done

          # Write member title in file ${{ inputs.outputFileName }}.md
          cat >${{ inputs.outputFileName }}.md <<EOF

        # GitHub Access Report - Status
        Generated at $timestamp

        ## Organization: **$ORG_NAME**

        ### Members

        | No | Username | Name | Role | Teams |
        | -- | -------- | ---- | ---- | ----- |
        EOF

          # Write member content in file ${{ inputs.outputFileName }}.md
          length=${#users[@]}
          # Range of length of users
          for i in $(seq 1 "$length"); do
            echo -n "| $i | ${users[$i - 1]} | " >>${{ inputs.outputFileName }}.md
            if [[ "${names[$i - 1]}" == "null" ]]; then
              echo -n " | " >>${{ inputs.outputFileName }}.md
            else
              echo -n "${names[$i - 1]} | " >>${{ inputs.outputFileName }}.md
            fi
            if [[ "${roles[$i - 1]}" == "admin" ]]; then
              echo -n "<ins>**${roles[$i - 1]}**</ins> | " >>${{ inputs.outputFileName }}.md
            else
              echo -n "${roles[$i - 1]} | " >>${{ inputs.outputFileName }}.md
            fi
            for id in "${!team_content[@]}"; do
              for team_name in ${team_content[$id]}; do
                if [ "${users[$i - 1]}" == "$team_name" ]; then
                  echo -n "$id<br>" >>${{ inputs.outputFileName }}.md
                fi
              done
            done

            echo "|" >>${{ inputs.outputFileName }}.md
          done

          # Repositories
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$ORG_API_URL/repos")

          response_repo_name=$(echo "$response" | jq -r '.[].name')
          response_repo_visibility=$(echo "$response" | jq -r '.[].visibility')

          repo_name=()
          repo_visibility=()
          for name in $response_repo_name; do
            repo_name+=("$name")
          done
          for visibility in $response_repo_visibility; do
            repo_visibility+=("$visibility")
          done

          # Fetch CODEOWNERS file
          fetch_and_format_codeowners() {
              repo_name=$1
              paths=("CODEOWNERS" ".github/CODEOWNERS" "docs/CODEOWNERS")
              formatted_codeowners=""
              codeowners_content=""
        
              for path in "${paths[@]}"; do
                  response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORG_NAME/$repo_name/contents/$path")
                  if echo "$response" | grep -q "download_url"; then
                      download_url=$(echo "$response" | grep "download_url" | cut -d '"' -f 4)
                      codeowners_content=$(curl -s "$download_url")
                      while IFS= read -r line; do
                        # Skip comments and empty lines
                        if [[ "$line" =~ ^# ]] || [[ -z "$line" ]]; then
                            continue
                        fi
                        formatted_codeowners+="${line}<br>"
                      done <<< "$codeowners_content"
                      break
                  fi
              done
        
              echo "$formatted_codeowners"
          }

          # Write repository title in file ${{ inputs.outputFileName }}.md
          cat >>${{ inputs.outputFileName }}.md <<EOF

        ### Repositories

        | No | Repo Name | Visibility | Branches | CODEOWNERS | Members/Teams | Role |
        | -- | --------- | ---------- | -------- | ---------- | ------------- | ---- |
        EOF

          length_repo="${#repo_name[@]}"
          declare -A repo_perms_error
          for i in $(seq 1 "$length_repo"); do

            REPO_API_URL="https://api.github.com/repos/$ORG_NAME/${repo_name[$i - 1]}"

            # Fetch Members and Roles
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$REPO_API_URL/collaborators")
            if jq -e '.message' <<<"$response" >/dev/null 2>&1; then
              repo_perms_error["${repo_name[$i - 1]}"]=$(echo "$response" | jq -r '.message')
              response_repo_member=""
              response_repo_member_roles=""
            else
              response_repo_member=$(echo "$response" | jq -r '.[].login')
              response_repo_member_roles=$(echo "$response" | jq -r '.[].role_name')
            fi

            #            repo_member_name=()
            #            repo_member_role=()
            #            for name in $response_repo_member; do
            #              repo_member_name+=("$name")
            #            done
            #            for role in $response_repo_member_roles; do
            #              repo_member_role+=("$role")
            #            done
            declare -A repo_member_roles
            for i in "${!repo_member_name[@]}"; do
              repo_member_roles["${repo_member_name[$i]}"]="${repo_member_role[$i]}"
            done

            # Fetch Teams
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$REPO_API_URL/teams")
            if jq -e '.message' <<<"$response" >/dev/null 2>&1; then
              response_repo_team_name=""
              response_repo_team_permission=""
              response_repo_team_slug=""
            else
              response_repo_team_name=$(echo "$response" | jq -r '.[].name')
              response_repo_team_permission=$(echo "$response" | jq -r '.[].permission')
              response_repo_team_slug=$(echo "$response" | jq -r '.[].slug')
            fi

            repo_team_name=()
            repo_team_permission=()
            repo_team_members=()
            for team_name in $response_repo_team_name; do
              repo_team_name+=("$team_name")
              team_members_response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$ORG_NAME/teams/$team_name/members")
              mapfile -t team_members < <(echo "$team_members_response" | jq -r '.[].login')
              repo_team_members+=("${team_members[@]}")
            done
            for team_perm in $response_repo_team_permission; do
              if [[ "$team_perm" == "push" ]]; then
                repo_team_permission+=("write")
              elif [[ "$team_perm" == "pull" ]]; then
                repo_team_permission+=("read")
              else
                repo_team_permission+=("$team_perm")
              fi
            done
        
            # Fetch Branches
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$REPO_API_URL/branches")
            if jq -e '.message' <<<"$response" >/dev/null 2>&1; then
                repo_branches_error["${repo_name[$i - 1]}"]=$(echo "$response" | jq -r '.message')
                response_repo_branches=""
            else
                response_repo_branches=$(echo "$response" | jq -r '.[].name')
            fi
        
            repo_branches=()
            for branch in $response_repo_branches; do
            repo_branches+=("$branch")
            done
        
            # Fetch CODEOWNERS
            formatted_codeowners=$(fetch_and_format_codeowners "${repo_name[$i - 1]}")
            if [[ -z "$formatted_codeowners" ]]; then
                formatted_codeowners="No CODEOWNERS file found"
            fi
        
            # Write repository content in file ${{ inputs.outputFileName }}.md
            echo -n "| $i | ${repo_name[$i - 1]} | ${repo_visibility[$i - 1]} | " >>${{ inputs.outputFileName }}.md
            echo "repo name = ${repo_name[$i - 1]}"

            # Range of length of members from repo
            length_repo_members="${#repo_member_roles[@]}"
            length_repo_groups="${#repo_team_name[@]}"
            length_repo_branches="${#repo_branches[@]}"
        
            # Branches
            if [[ $length_repo_branches != 0 ]]; then
                for j in $(seq 0 "$(($length_repo_branches - 1))"); do
                    echo -n "${repo_branches[$j]}<br>" >>${{ inputs.outputFileName }}.md
                done
            else
                if [[ -n "${repo_branches_error[${repo_name[$i - 1]}]}" ]]; then
                    echo -n "Error fetching branches: ${repo_branches_error[${repo_name[$i - 1]}]}<br>" >>${{ inputs.outputFileName }}.md
                else
                    echo -n "No branches<br>" >>${{ inputs.outputFileName }}.md
                fi
            fi
        
            echo -n " | " >>${{ inputs.outputFileName }}.md
        
            # CODEOWNERS append
            echo -n "$formatted_codeowners | " >>${{ inputs.outputFileName }}.md

            # Members/Teams
            if [[ $length_repo_members != 0 ]] || [[ $length_repo_groups != 0 ]]; then
              if [[ $length_repo_members != 0 ]]; then
                echo -n "**Members**<br>" >>${{ inputs.outputFileName }}.md
                for member in "${!repo_member_roles[@]}"; do
                  echo -n "$member<br>" >>${{ inputs.outputFileName }}.md
                done
              fi
              if [[ $length_repo_groups != 0 ]]; then
                echo -n "**Teams**<br>" >>${{ inputs.outputFileName }}.md
                for j in $(seq 0 "$length_repo_groups"); do
                  echo -n "${repo_team_name[$j]}<br>" >>${{ inputs.outputFileName }}.md
                  echo "repo team = ${repo_team_name[$j-1]}"
                done
              fi

              echo -n " | " >>${{ inputs.outputFileName }}.md

              # Roles
              if [[ $length_repo_members != 0 ]]; then
                echo -n "<br>" >>${{ inputs.outputFileName }}.md
            
                for j in $(seq 0 "$length_repo_members"); do
                  member_role="${repo_member_roles[${repo_member_name[$j]}]}"
                  org_role="${roles[${users[@]/$repo_member_name[$j]}]}"
            
                  if [[ " ${repo_team_members[@]} " =~ " ${repo_member_name[$j]} " ]]; then
                    team_role=""
                    for k in $(seq 0 "$length_repo_groups"); do
                      if [[ " ${team_content[${repo_team_name[$k]}]} " =~ " ${repo_member_name[$j]} " ]]; then
                        if [[ "${repo_team_permission[$k]}" == "admin" && "$team_role" != "admin" ]]; then
                          team_role="admin"
                        elif [[ "${repo_team_permission[$k]}" == "maintain" && "$team_role" != "admin" && "$team_role" != "maintain" ]]; then
                          team_role="maintain"
                        elif [[ "${repo_team_permission[$k]}" == "write" && "$team_role" != "admin" && "$team_role" != "maintain" && "$team_role" != "write" ]]; then
                          team_role="write"
                        elif [[ "${repo_team_permission[$k]}" == "read" && "$team_role" != "admin" && "$team_role" != "maintain" && "$team_role" != "write" && "$team_role" != "read" ]]; then
                          team_role="read"
                        fi
                      fi
                    done
            
                    if [[ "$team_role" == "admin" || "$member_role" == "admin" ]]; then
                      echo -n "admin(team)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$team_role" == "maintain" || "$member_role" == "maintain" ]]; then
                      echo -n "maintain(team)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$team_role" == "write" || "$member_role" == "write" ]]; then
                      echo -n "write(team)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$team_role" == "read" || "$member_role" == "read" ]]; then
                      echo -n "read(team)<br>" >>${{ inputs.outputFileName }}.md
                    else
                      echo -n "${org_role}<br>" >>${{ inputs.outputFileName }}.md
                    fi
                  else
                    if [[ "$member_role" == "admin" ]]; then
                      echo -n "admin(repo)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$member_role" == "maintain" ]]; then
                      echo -n "maintain(repo)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$member_role" == "write" ]]; then
                      echo -n "write(repo)<br>" >>${{ inputs.outputFileName }}.md
                    elif [[ "$member_role" == "read" ]]; then
                      echo -n "read(repo)<br>" >>${{ inputs.outputFileName }}.md
                    else
                      echo -n "${org_role}<br>" >>${{ inputs.outputFileName }}.md
                    fi
                  fi
                done
              fi
          
              if [[ $length_repo_groups != 0 ]]; then
                echo -n "<br>" >>${{ inputs.outputFileName }}.md
                for j in $(seq 0 "$length_repo_groups"); do
                  echo -n "${repo_team_permission[$j]}<br>" >>${{ inputs.outputFileName }}.md
                done
              fi
              echo " |" >>${{ inputs.outputFileName }}.md

            else
              echo " | |" >>${{ inputs.outputFileName }}.md
            fi
          done

          # Provide error messages in case these exist
          if [[ "${#repo_perms_error[@]}" -gt 0 ]]; then
            echo ""
            echo "### You have the following errors:" >>${{ inputs.outputFileName }}.md
            echo ""
            for i in "${!repo_perms_error[@]}"; do
              echo "- Repo: $i" >>${{ inputs.outputFileName }}.md
              echo "    - Message: ${repo_perms_error[$i]}" >>${{ inputs.outputFileName }}.md
            done
            echo "" >>${{ inputs.outputFileName }}.md
            echo "This can be caused by not having permission on those repos." >>${{ inputs.outputFileName }}.md
          fi
        fi
        
        current_date=$(date +"%d %B %Y")
        ls -a
        git config --global user.email "your@email.com"
        git config --global user.name "${{ github.actor }}"
        git add .
        git commit -m "File ${{ inputs.outputFileName }}.md - Generated at $current_date"
        git push

      shell: bash
